### PR TITLE
Improve README + Minor Corrections

### PR DESCRIPTION
**Pull request by x4d3**
- Remove "override managed version" warning
- Add missing serialVersionUID
- Improve README adding Troubleshooting

### CODE REVIEW

**Comment by x4d3** [comment]
Hello @tom59 Could you please review ? Thank you.

**Comment by crystalmark** [comment]
Hi @x4d3 Sorry for the delay, I've just noticed this PR.  Would you bring your fork up-to-date with the latest master and I'll review asap?  Thanks.

**Comment by x4d3** [comment]
Hello @crystalmark 
All done.
Regards,

**Comment by crystalmark** [comment]
@x4d3 Thanks for the PR.  Please send more!

**Pull request merged**
